// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgzulntbmbheopxxmcpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnenVsbnRibWJoZW9weHhtY3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDU3OTYsImV4cCI6MjA2NTIyMTc5Nn0.0IXOmf5dX4RHMQ8ukkc60AkL1vlLZui5Y2g3sV09kiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);